### ISSUE TITLE
Error on enter Sonoff credentials

### ISSUE THREAD

**Issue by stmaslakoff** [nick7zmail/MajorDoMo_dev_sonoff#5]
> 1366: Incorrect integer value: '' for column `db_terminal`.`dev_sonoff_devices`.`ID` at row 1

Добрый день! Получаю такую ошибку при вводе данных для аккаунта ewelink. Думаю, что причина в строке 33 в dev_sonoff_devices_scan.inc.php : 
> $rec['ID']='';
Т.к. ID - это AUTO_INCREMEN поле, то предлагаю убрать эту строку

**Comment by nick7zmail** [comment]
Эту строку убирать нельзя, в противном случае $rec['ID'] может остаться от предыдущей записи. 
Можно только более правильно попробовать написать. Попробуйте
$rec['ID']='';
заменить на 
unset($rec['ID']);

**Comment by stmaslakoff** [comment]
@nick7zmail должно помочь. Сможете добавить в код?

**Comment by nick7zmail** [comment]
Должно помочь теоретически. На практике - совсем не факт. Проверьте у себя, если решает проблему - добавлю в код.

**Comment by stmaslakoff** [comment]
@nick7zmail спасибо! Помогло - только нужно было еще ниже поправить: 
> $rec_params['ID']='';

PR готов к мерджу https://github.com/nick7zmail/MajorDoMo_dev_sonoff/pull/6
