### ISSUE TITLE
Ошибка объявления поля

### ISSUE THREAD

**Issue by sergejey** [nick7zmail/MajorDoMo_dev_sonoff#7]
https://github.com/nick7zmail/MajorDoMo_dev_sonoff/blob/6ad96bc6207fcbe8e6b181cc7f74aa4695debbfa/modules/dev_sonoff/dev_sonoff.class.php#L990

Я так понимаю что здесь должно быть dev_sonoff_data -- иначе постоянная ошибка об отсутствующем поле, что система пытается полечить переустановкой модулей и в итоге всё очень нестабильно начинает работать.

**Comment by nick7zmail** [comment]
fixed
